### ISSUE TITLE
Not possible to configure `clickhouse` when having external clickhouse installation

### ISSUE THREAD

**Issue by grzesuav** [coroot/helm-charts#19]
Coroot helm chart has a `clickhouse` chart as dependency, on condition `clikchouse.enabled`. However setting it to `false` disables clickhouse completely - https://github.com/coroot/helm-charts/blob/main/charts/coroot/templates/deployment.yaml#L48 .

I have clikchouse installed externally and I want to configure coroot to use it, currently there is no such possbility

**Comment by trungtien** [comment]
hi @def  
Please support the installation of Coroot from the Helm chart with an external ClickHouse. :)

**Comment by def** [comment]
You can disable ClickHouse installation by setting clickhouse.enabled to false, and then configure ClickHouse credentials using [`corootCE.env`](https://github.com/coroot/helm-charts/blob/main/charts/coroot/templates/deployment.yaml#L69C28-L69C40).
