### ISSUE TITLE
Cooroot cluster agent PVC and value for `wal`

### ISSUE THREAD

**Issue by grzesuav** [coroot/helm-charts#22]
IN new cluster agent version there is `wal` flag, which would require PVC (probably) and some default setup, like is done in `docker-compose` - https://github.com/coroot/coroot/blob/main/deploy/docker-compose.yaml#L53

Currently is is handled like
```yaml
            - name: METRICS_WAL_DIR
              value: "{{ .Values.corootClusterAgent.config.metrics.wal_dir }}"
```
and there is no possibility to configure PVC for cluster agent

**Comment by grzesuav** [comment]
https://github.com/coroot/helm-charts/blob/coroot-0.13.0/charts/coroot/templates/cluster-agent.yaml#L106

**Comment by def** [comment]
I don't think we need to use PVC here. This WAL can be considered as a temporary storage to keep metrics before flushing them to Coroot.
