### ISSUE TITLE
Node-Agent is unable to collect Data from Talos-Linux 1.7.5 Kubernetes Nodes

### ISSUE THREAD

**Issue by natorus87** [coroot/helm-charts#25]
I think Talos is different from normal Linux Distributions, because the System is read-only, and there is no User-Environment. Maybe the Proc Paths are others. I have attached the Logs.

[node-agent.log](https://github.com/user-attachments/files/16521484/node-agent.log)

**Comment by def** [comment]
This repo is just for Helm charts, not for Coroot bug reports. Closing this one, but feel free to open a new issue at https://github.com/coroot/coroot
